"""Added model for monitoring changes on automate server settings table

Revision ID: 324bf2ef9fea
Revises: ea085e9447f7
Create Date: 2024-03-31 15:38:14.371023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324bf2ef9fea'
down_revision: Union[str, None] = 'ea085e9447f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
