"""New model for server settings created

Revision ID: 655a843dc911
Revises: d9fb94bab883
Create Date: 2024-03-31 10:59:27.431888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '655a843dc911'
down_revision: Union[str, None] = 'd9fb94bab883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'Enabled',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'Enabled',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
    # ### end Alembic commands ###
