"""Added extra models

Revision ID: 6cb7fa807552
Revises: 05abf5bc2939
Create Date: 2024-01-08 17:06:26.146045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb7fa807552'
down_revision: Union[str, None] = '05abf5bc2939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resourceID', sa.String(length=50), nullable=False),
    sa.Column('last_connectedID', sa.String(length=50), nullable=False),
    sa.Column('last_connected_machinename', sa.String(length=50), nullable=False),
    sa.Column('last_connect_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automate-events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('event_date_time', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('event_description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('primary_constructID', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'eventID')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resourceID', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=150), nullable=False),
    sa.Column('parentID', sa.String(length=50), nullable=False),
    sa.Column('completion_state', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instanceID', sa.Integer(), nullable=False),
    sa.Column('WorkflowID', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('automate_userID', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_table('tasks')
    op.drop_table('automate-events')
    op.drop_table('agents')
    # ### end Alembic commands ###
