"""AutomateServerSettings model, changed behaviour columns

Revision ID: a22c35b6bcd6
Revises: ea253bdf4edb
Create Date: 2024-03-31 15:51:01.915987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a22c35b6bcd6'
down_revision: Union[str, None] = 'ea253bdf4edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Assuming 'PK__change_l__3213E83F7F3469FE' is the constraint name for the 'id' column
    op.execute("ALTER TABLE change_log_automate_server_settings DROP CONSTRAINT PK__change_l__3213E83F7F3469FE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_log_automate_server_settings', 'id')
    op.drop_column('change_log_automate_server_settings', 'record_id')
    op.add_column('change_log_automate_server_settings', sa.Column('ID', sa.String(length=38), nullable=False))
    op.alter_column('change_log_automate_server_settings', 'global_triggering',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_log_automate_server_settings', sa.Column('record_id', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('change_log_automate_server_settings', sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.alter_column('change_log_automate_server_settings', 'global_triggering',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.drop_column('change_log_automate_server_settings', 'ID')
    # ### end Alembic commands ###
