"""extended workflow model

Revision ID: de4628a6bc9e
Revises: c7fe57c1f396
Create Date: 2024-03-04 13:43:45.661956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'de4628a6bc9e'
down_revision: Union[str, None] = 'c7fe57c1f396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'WorkflowName',
               existing_type=sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'ResourceType',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflows', 'CompletionState',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflows', 'Notes',
               existing_type=mssql.NTEXT(length=1073741823, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'CreatedBy',
               existing_type=sa.NVARCHAR(length=38, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('workflows', 'CreatedOn',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('workflows', 'Version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflows', 'VersionDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('workflows', 'Empty',
               existing_type=sa.SMALLINT(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('workflows', 'Enabled',
               existing_type=sa.SMALLINT(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('workflows', 'Removed',
               existing_type=sa.SMALLINT(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('workflows', 'ResultText',
               existing_type=mssql.NTEXT(length=1073741823, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'LockedBy',
               existing_type=sa.NVARCHAR(length=38, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'NumberOfTasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflows', 'UpdatedOn',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'UpdatedOn',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('workflows', 'NumberOfTasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflows', 'LockedBy',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(length=38, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'ResultText',
               existing_type=sa.Text(),
               type_=mssql.NTEXT(length=1073741823, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'Removed',
               existing_type=sa.Boolean(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('workflows', 'Enabled',
               existing_type=sa.Boolean(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('workflows', 'Empty',
               existing_type=sa.Boolean(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('workflows', 'VersionDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('workflows', 'Version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflows', 'CreatedOn',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('workflows', 'CreatedBy',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(length=38, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('workflows', 'Notes',
               existing_type=sa.Text(),
               type_=mssql.NTEXT(length=1073741823, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('workflows', 'CompletionState',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflows', 'ResourceType',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflows', 'WorkflowName',
               existing_type=sa.String(length=255),
               type_=sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text('(NULL)'))
    # ### end Alembic commands ###
