"""AutomateServerSettings model, changed behaviour rowupdatedOn column

Revision ID: ea085e9447f7
Revises: ca2a3b1247f2
Create Date: 2024-03-31 11:22:38.807354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea085e9447f7'
down_revision: Union[str, None] = 'ca2a3b1247f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
