"""Added model for monitoring changes on automate server settings table

Revision ID: ea253bdf4edb
Revises: 324bf2ef9fea
Create Date: 2024-03-31 15:40:24.191337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea253bdf4edb'
down_revision: Union[str, None] = '324bf2ef9fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log_automate_server_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('global_triggering', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_log_automate_server_settings')
    # ### end Alembic commands ###
